# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  playstudiosleaderboardapi:
    image: playstudiosleaderboardapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5284:5284
